### ISSUE TITLE
INVOKE accepts PTR BYTE as LPWSTR argument

### ISSUE THREAD

**Issue by vid512** [Terraspace/UASM#111]
Following compiles without any warning:
`option casemap:none    ;needed for windows.inc
option fieldalign:8
option stackbase:rsp
option frame:auto
option literals:on

;please fix the path to WinInc
include d:\dev\_tools\jwasm\WinInc\include\windows.inc

.code
bufA db 10 dup(?)
bufW dw 10 dup(?)

invoke GetEnvironmentVariableW, addr [bufW], addr [bufA], 10

end
`

The declaration of GetEnvironmentVariableW is: `@DefProto WINBASEAPI, GetEnvironmentVariableW, stdcall, , <:LPWSTR, :LPWSTR, :DWORD>, 12`

**Comment by john-terraspace** [comment]
I don't believe this is a bug exactly. Type checking is limited to the primary type, so in this case it's validating pointer against pointer (qword v qword) as opposed to taking the type checking further to the types actually pointed to BY the pointer. I  think you'd have a similar result if you had a strongly typed parameter on the proto, say PBOX typedef PTR Box  and you passed an address in.

I wouldn't be inclined to change this behaviour as it might impact other intentional uses, for example a memory fill function which takes it's address typed, say PTR DWORD, but the actual array you pointing at happens to be a byte array.. at least that would then require type coercion/casting.

**Comment by vid512** [comment]
I am surprised, for whatever reason, I was convinced MASM/UASM did check the entire type. 

Anyway, what do you think about adding the full type checking as a /W4 warning, so it can be easily ignored/disabled by anyone who doesn't want it? It seems to me like a feature which could help to catch bugs early in a cleanly written project.

**Comment by john-terraspace** [comment]
It’s a good idea, I will add it to the backlog 😊
