### ISSUE TITLE
Debug symbols in Visual Studio 2019

### ISSUE THREAD

**Issue by plastovicka** [Terraspace/UASM#142]
CodeView4 format is not supported since Visual Studio 2019 (platform toolset v142). Only variables of primitive types (integers and floats) are visible in the debubber. Variables of strings, arrays and structures are missing.
You can test it on this simple ASM source:
```
.data
message	db "Hello, world !",0
```

I think it should not be hard to fix this problem. Most of the new **CodeView8** format types are already declared in header file **dbgcv.h**. But it's also necessary to change many properties from `uint_16` to `uint_32`.

```
enum cv_leaf_indices {
    ...
    LF_ARRAY = CV8_LF_ARRAY,
    ...
}

struct cv_typerec_array { /* LF_ARRAY v2.10: added */
    struct cv_typerec tr;
    uint_32 elemtype;
    uint_32 idxtype;
    uint_32 length;  /* numeric leaf */
    // length-prefixed name
};
```

**Comment by john-terraspace** [comment]
I did look at this once before and it turned out to be a lot more problematic than first thought.

 

Gathering some links for technical reference:

https://github.com/yasm/yasm/blob/master/modules/dbgfmts/codeview/cv8.txt

 

https://fossies.org/linux/nasm/output/codeview.c

 

http://ftp.openwatcom.org/devel/docs/CodeView.pdf

 

https://gist.github.com/skochinsky/2d73bba6bbf9692614cb

 

I believe ASMC has implemented  CV8 support, I will ask it’s author about the scope of changes required.

**Comment by john-terraspace** [comment]
This should be done in 2.51/52+
