### ISSUE TITLE
assume reg:error with [reg]

### ISSUE THREAD

**Issue by vid512** [Terraspace/UASM#149]
When register assumed to error is used in memory addressing, it doesn't throw error. I would expect any use of register to throw error.
```
        assume r11:error
        mov [r11], al                  ; works fine
```

**Comment by john-terraspace** [comment]
Fixed in v2.53 branch.

 

From: vid512 ***@***.***> 
Sent: Thursday, May 27, 2021 2:16 PM
To: Terraspace/UASM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Terraspace/UASM] assume reg:error with [reg] (#149)

 

When register assumed to error is used in memory addressing, it doesn't throw error. I would expect any use of register to throw error.

        assume r11:error
        mov [r11], al                  ; works fine
