### ISSUE TITLE
Local symbol turned into a public symbol

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#75]
Sorry, I can't make a small reproducible case.   Below is a nuisance bug.  I believe generated code is correct, just a little harder to debug as backtrace gives less than useful names.  Uasm 2.46 dated Dec 17.

In a macro I declare a symbol LOCAL, but when I disassemble code in gdb, the local symbol seems to have become public.   Here is a gdb disassembly snipet:

  ` 0x000000000078cbca <zfft_r4dwpn_128_ac_1_CORE+116>:	callq  *%rax`
  ` 0x000000000078cbcc <zfft_r4dwpn_128_ac_1_CORE+118>:	mov    %rbx,%r11`
  ` 0x000000000078cbcf <??0211+0>:	mov    0x40(%r11),%rbp`
  ` 0x000000000078cbd3 <??0211+4>:	mov    0x150(%r11),%rsi`

Here is a link to the source code:   https://www.dropbox.com/s/6tkpghi0edlk95c/src.tar.gz?dl=0
Hopefully, I included all you need and weeded out the extraneous stuff.  The file to assemble is zr4dwpn.asm, uasm switches defined in compil64.

The  zr4dwpn.lst file shows the local symbol as:
`??0211 . . . . . . . . . . . . .        L Near          3DC4h _TEXT FASTCALL`

The relevant source code is in zr4dwpnpass1sc.mac.  The macro is zr4dwpn_pass1sc128ac, local symbol c0b.

**Comment by john-terraspace** [comment]
Thanks, will take a look and report back!

 

John

**Comment by john-terraspace** [comment]
I’ve assembled it and can see the symbol/label you are referring to. I don’t think it has become public, it is listed in the .lst files complete symbol table dump which is expected.

 

I’m assuming that this:

0x000000000078cbcf <??0211+0>: mov 0x40(%r11),%rbp
0x000000000078cbd3 <??0211+4>: mov 0x150(%r11),%rsi

 

Is this in source:

c0b:        start_timer 16

                mov       rbp, DATA_ADDR                                             ;; Get source address

                mov       rsi, scratch_area                               ;; Get address of scratch area

 

Under Coff debugging I believe the debug entries simply use the enclosing proc and an offset, however for Nix without debug info (DWARF) support it’s using the symbol table entry linked

to that address, which is why you see the ??0211+0

(So it’s GDB trying to be helpful by linking the related symbol table entry name even though there is technically no debug data).

 

I would hope the debugging situation on Nix/OSX will improve in the next several releases when we add support for DWARF.

**Comment by gwoltman** [comment]
When I tried creating a small test case:  https://www.dropbox.com/s/nhjvbx3vqsr52fo/foo.asm?dl=0

The symbol table looks different (from the .lst file):

`  ??0000 . . . . . . . . . . . .        L Near   00000024 _TEXT`

Note there is no length or FASTCALL specified for the local.  Whereas the problem case shows this in the .lst file:
`??0211 . . . . . . . . . . . . . L Near 3DC4h _TEXT FASTCALL`

For some reason, UASM is generating different symbol table entries for the two nearly identical cases.

**Comment by john-terraspace** [comment]
That is interesting,

 

I’ll give this testcase a go, the only thing I can think that would cause that difference in the result is either the label becomes the target of a call/invoke OR for some reason FASTCALL is the language identifier/type that is assigned to it due to the surrounding proc in which it is expanded being of type fastcall.

**Comment by john-terraspace** [comment]
I believe this query is resolved due to the use of the OPTION NOSCOPED, can I close it ?

**Comment by gwoltman** [comment]
If you think that is appropriate.  I think the current behavior is a little
inconsistent, but it certainly doesn't bother me.  I have no idea why
OPTION NOSCOPED is specified.  It's been that way for 20 years...

**Comment by john-terraspace** [comment]
Alright, I will do so. I believe the noscoped works exactly as masm’s does, from what I’ve  tested thus far.. it’s not an option I’ve ever used personally.

 

PS, the vmovupd displacement issue is fixed and the update will be up shortly.
