### ISSUE TITLE
No explicit license terms in top-level directory

### ISSUE THREAD

**Issue by jserv** [Terraspace/UASM#93]
After quick browsing the source tree, I found there is no explicit file describing license terms used in this project. Portions of this project were derived from Open Watcom Project, which is copyrighted as 1983-2002 Sybase, Inc., and others were claimed as public domain. Can you clarify this?

**Comment by john-terraspace** [comment]
Hi,

 

UASM as derived from JWASM and then from WASM has obviously had to keep the Open Watcom License as the original WASM source was published under it.

The OWL requires that any modified source is published under the same conditions so it’s not as forgiving as GPL etc in that you cannot create proprietary closed-source application based on the source, but as long as the modified version is also OSS under the same license that is fine.

 

Personally I’d love to get rid of the OSL and go GPL, but I’m not sure if that is at all possible given the project’s origins. I estimate at least 60% of the code has been completely re-built since WASM so I’m not sure how relevant the license terms are now, but the origin will always be WASM.

 

Perhaps one day some bro-bono copyright lawyer would be able to advise and we could adjust the terms 😊
